### PR TITLE
Issue #2

### PR DESCRIPTION
**Pull request by l0n3star**
Added library function to show frost and rain warnings

### CODE REVIEW

**Comment by petteripitkanen** [comment]
Thank you for the PR. The Dark Sky API looks useful, but it might be that the reported alerts are of only secondary interest, we are looking for normal conditions like "there will be rain in the next few days" or "there will be frost early next morning" or "we are in a period of drought" that will help the gardener to take appropriate actions. Also, we might need to divide the task of finding weather warnings to smaller steps, it seems that the detection for rain, frost and drought also depends on weather data for the past few days, for instance the condition for frost could be something like this: _during the day temperature is above 0 celsius AND during the night temperature drops below 0 AND for the past week there has not been frost every night_.

I have opened #99 for collecting weather data. This is with farmOS because we are currently in the process of defining more clearly what is the structure and scope of powerplant, and leaning towards a solution where powerplant would become a component of a system that helps to manage a _single farm_. Main components of this system would include MediaWiki (using templates from practicalplants.org) for managing information about crops, and farmOS for record keeping. Powerplant would collect all available information from other components and provide permaculture-oriented assistance for the gardener. Collecting weather data looks like a good starting point for beginning to experiment with farmOS.

After #99 is done it is possible to combine the collected weather data from farmOS with a forecast from Dark Sky API to accurately determine weather warning conditions. Then the weather warnings could be pushed to farmOS.

Some comments about the PR:
* Consider using _feature branches_, see https://www.atlassian.com/git/tutorials/comparing-workflows/feature-branch-workflow, this might help when working on multiple features/PRs on the same repository.
* Please don't update generated documentation in the same commit with code changes, try to keep commits compact to make it easier for the reviewers to immediately see what they are about.
* Actually the generated documentation doesn't belong to git history, we should maybe fix this by moving it to the `gh-pages` branch.
* We use `secrets.js` for configuration variables like `DARKSKY_API_KEY`.
* Consider dividing the code to a fetching function that uses the API to get a `weatherResult`, and to a parsing function that is given the `weatherResult` and that returns a list of relevant alerts. This division helps when there is also a need to obtain other sort of properties from a `weatherResult`, and it also makes it possible to test the parsing function separately without using the API or `sinon`.

**Comment by l0n3star** [comment]
Thanks for feedback.  Going forward will use feature branches.

**Comment by l0n3star** [comment]
According to SO (https://stackoverflow.com/questions/42381557/changing-source-branch-for-pr-on-github) I can't change source branch once PR submitted.  I'd like to close this one and submit a new PR when I'm ready.  Are you OK with this?

**Comment by petteripitkanen** [comment]
Seems okay to me.

**Pull request closed without merging**
